### ISSUE TITLE
How to python in windows?

### ISSUE THREAD

**Issue by zhoufy20** [AIforGreatGood/charge3net#12]
Hi, developers of `charge3net`:

I am extremely interesting in this userful tools, But there are several Config problem in windows without `srun`, I am writing to ask for some guidance on how to train in windows?

```
# Copyright (c) 2023, MASSACHUSETTS INSTITUTE OF TECHNOLOGY
# Subject to FAR 52.227-11 - Patent Rights - Ownership by the Contractor (May 2014).
defaults:
  - model: e3_density
  - data: mp_perturbed
  - override hydra/launcher: submitit_slurm
  - _self_

input_dir:  # arbitrary directory containing .npy and .pkl files, with filelist.txt, split.json, and probe_counts.csv 
lmax: 4
checkpoint_path: ./models/charge3net_mp.pt
cube_dir: ${hydra:run.dir}

# tensorboard, logs, and tmp files
log_dir: ${hydra:run.dir}

# number of nodes
nnodes: 2
# number of processes/devices per node
nprocs: 2


seed: 42
cutoff: 4.0
batch_size: 1
lr: 0.005

hydra:
  job:
    name: prediction_lmax_${lmax}
  run: 
    dir: ${input_dir}/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${hydra.run.dir}

  launcher:
    partition: gaia
    nodes: ${nnodes}
    tasks_per_node: 1 # note, multiprocessing will handle multitasking per node
    constraint: xeon-g6
    timeout_min: 20000
    additional_parameters:
      gres: gpu:volta:2
      exclusive: True
      distribution: nopack
  callbacks:
    log_job_return:
      _target_: hydra.experimental.callbacks.LogJobReturnCallback


data:
  batch_size: ${batch_size}
  train_workers: 8
  val_workers: 1
  pin_memory: False
  train_probes: 200
  val_probes: 400
  test_probes: 
  data_root: ${input_dir}/filelist.txt
  split_file: ${input_dir}/split.json
  grid_size_file: ${input_dir}/probe_counts.csv
  graph_constructor:
    cutoff: ${cutoff}
    disable_pbc: False


model:
  optimizer:
    lr: ${lr}
  lr_scheduler:
    beta: 3e3
  model:
    lmax: ${lmax}
```

What is `mp_perturbed`?
